import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import processing_data
from processing_data import df, country_goal_data, goal_metric_data


uk_goal1 = country_goal_data('United Kingdom', 'Goal7', df)

countries = [
    'Aruba',
    'Angola',
    'Albania',
    'United Arab Emirates',
    'Argentina',
    'Armenia',
    'Antigua and Barbuda',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Burundi',
    'Belgium',
    'Benin',
    'Burkina Faso',
    'Bangladesh',
    'Bulgaria',
    'Bahrain',
    'Bahamas, The',
    'Bosnia and Herzegovina',
    'Belarus',
    'Belize',
    'Bolivia',
    'Brazil',
    'Barbados',
    'Brunei Darussalam',
    'Bhutan',
    'Botswana',
    'Central African Republic',
    'Canada',
    'Switzerland',
    'Chile',
    'China',
    "Cote d'Ivoire",
    'Cameroon',
    'Congo, Dem. Rep.',
    'Congo, Rep.',
    'Colombia',
    'Comoros',
    'Cabo Verde',
    'Costa Rica',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Germany',
    'Dominica',
    'Denmark',
    'Dominican Republic',
    'Algeria',
    'Ecuador',
    'Egypt, Arab Rep.',
    'Eritrea',
    'Spain',
    'Estonia',
    'Ethiopia',
    'Finland',
    'Fiji',
    'France',
    'Gabon',
    'United Kingdom',
    'Georgia',
    'Ghana',
    'Gambia, The',
    'Guinea-Bissau',
    'Equatorial Guinea',
    'Greece',
    'Guatemala',
    'Guyana',
    'Hong Kong SAR, China',
    'Honduras',
    'Croatia',
    'Haiti',
    'Hungary',
    'Indonesia',
    'India',
    'Ireland',
    'Iran, Islamic Rep.',
    'Iraq',
    'Iceland',
    'Israel',
    'Italy',
    'Jamaica',
    'Jordan',
    'Japan',
    'Kazakhstan',
    'Kenya',
    'Kyrgyz Republic',
    'Cambodia',
    'Korea, Rep.',
    'Kuwait',
    'Lao PDR',
    'Lebanon',
    'Liberia',
    'St. Lucia',
    'Sri Lanka',
    'Lesotho',
    'Lithuania',
    'Luxembourg',
    'Latvia',
    'Macao SAR, China',
    'Morocco',
    'Moldova',
    'Madagascar',
    'Maldives',
    'Mexico',
    'North Macedonia',
    'Mali',
    'Malta',
    'Myanmar',
    'Montenegro',
    'Mongolia',
    'Mozambique',
    'Mauritania',
    'Mauritius',
    'Malawi',
    'Malaysia',
    'Namibia',
    'Niger',
    'Nigeria',
    'Nicaragua',
    'Netherlands',
    'Norway',
    'Nepal',
    'New Zealand',
    'Oman',
    'Pakistan',
    'Panama',
    'Peru',
    'Philippines',
    'Poland',
    "Korea, Dem. People's Rep.",
    'Portugal',
    'Paraguay',
    'West Bank and Gaza',
    'Qatar',
    'Romania',
    'Russian Federation',
    'Rwanda',
    'Saudi Arabia',
    'Senegal',
    'Singapore',
    'Solomon Islands',
    'Sierra Leone',
    'El Salvador',
    'Serbia',
    'Suriname',
    'Slovak Republic',
    'Slovenia',
    'Sweden',
    'Eswatini',
    'Seychelles',
    'Syrian Arab Republic',
    'Chad',
    'Togo',
    'Thailand',
    'Tajikistan',
    'Timor-Leste',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Tanzania',
    'Uganda',
    'Ukraine',
    'Uruguay',
    'United States',
    'Uzbekistan',
    'St. Vincent and the Grenadines',
    'Venezuela, RB',
    'Vietnam',
    'Vanuatu',
    'South Africa',
    'Zambia',
    'Zimbabwe',
]

